import React from "react";
import { Composition, registerRoot } from "remotion";
import { WhiteboardVideo } from "./WhiteboardVideo";

// These files are generated by the Python pipeline and copied to src/ by deploy_resources.py
import timeline from "./timeline.json";
import sceneConfig from "./scene-config.json";

const FPS = 30;
const WIDTH = 1920;
const HEIGHT = 1080;

const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="VideoMain"
      component={() => (
        <WhiteboardVideo
          timeline={timeline as any}
          storyboard={sceneConfig}
        />
      )}
      durationInFrames={timeline.totalFrames || 300}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
    />
  );
};

registerRoot(RemotionRoot);
